<?xml version="1.0"?>
<package format="3">
  <name>inorbit_scan_tools</name>
  <version>0.0.1</version>
  <description>Tools to adapt lidar scans for InOrbit visualization.</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>action_msgs</depend>
  <depend>control_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>stretch_nav2</depend>
  <depend>trajectory_msgs</depend>
  <exec_depend>tf2_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
